import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useSession, signIn, signOut } from "next-auth/react";
import styles from "../../styles/Home.module.css";
import { FC, useEffect } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (session && router?.query.broadcastId) {
      fetch(`/api/youtube/chat/${router?.query.broadcastId}`).then(
        async (response) => {
          const data = await response.json();
          console.log(data);
        }
      );
    }
  }, [router?.query, session]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
};

export default Home;
